<?php
namespace Database\Seeders;

use App\Models\SubkategoriSumberdana;
use App\Models\Sumberdana;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name'     => 'Test User',
            'email'    => 'test@example.com',
            'password' => Hash::make('123123123'),
            'role'     => 'admin',
        ]);

        Sumberdana::insert([
            [
                'id'               => 1,
                'nama_sumber_dana' => 'PENELITIAN KERJA SAMA LUAR NEGERI (SKEMA A)',
                'jenis_pendanaan'  => 'internal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 2,
                'nama_sumber_dana' => 'PENELITIAN KERJA SAMA DALAM NEGERI (SKEMA B)',
                'jenis_pendanaan'  => 'internal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 3,
                'nama_sumber_dana' => 'PENELITIAN NON KERJA SAMA EKSTERNAL (SKEMA C)',
                'jenis_pendanaan'  => 'internal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 4,
                'nama_sumber_dana' => 'PENELITIAN MANDIRI',
                'jenis_pendanaan'  => 'internal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 5,
                'nama_sumber_dana' => 'DRPTM',
                'jenis_pendanaan'  => 'eksternal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 6,
                'nama_sumber_dana' => 'Kedaireka',
                'jenis_pendanaan'  => 'eksternal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], [
                'id'               => 7,
                'nama_sumber_dana' => 'LPDP',
                'jenis_pendanaan'  => 'eksternal',
                'user_id_created'  => 1,
                'user_id_updated'  => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ]);

        SubkategoriSumberdana::insert([
            [
                'id'              => 1,
                'nama'            => 'Bahan Habis Pakai dan Peralatan',
                'nama_form'       => 'bahan_habis_pakai_dan_peralatan',
                'id_sumberdana'   => 1,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 2,
                'nama'            => 'Biaya Transportasi dan Perjalanan',
                'nama_form'       => 'biaya_transportasi_dan_perjalanan',
                'id_sumberdana'   => 1,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 3,
                'nama'            => 'Biaya Lainnya',
                'nama_form'       => 'biaya_lainnya',
                'id_sumberdana'   => 1,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 4,
                'nama'            => 'Bahan Habis Pakai dan Peralatan',
                'nama_form'       => 'bahan_habis_pakai_dan_peralatan',
                'id_sumberdana'   => 2,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 5,
                'nama'            => 'Biaya Transportasi dan Perjalanan',
                'nama_form'       => 'biaya_transportasi_dan_perjalanan',
                'id_sumberdana'   => 2,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 6,
                'nama'            => 'Biaya Lainnya',
                'nama_form'       => 'biaya_lainnya',
                'id_sumberdana'   => 2,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 7,
                'nama'            => 'Bahan Habis Pakai dan Peralatan',
                'nama_form'       => 'bahan_habis_pakai_dan_peralatan',
                'id_sumberdana'   => 3,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 8,
                'nama'            => 'Biaya Transportasi dan Perjalanan',
                'nama_form'       => 'biaya_transportasi_dan_perjalanan',
                'id_sumberdana'   => 3,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 9,
                'nama'            => 'Biaya Lainnya',
                'nama_form'       => 'biaya_lainnya',
                'id_sumberdana'   => 3,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 10,
                'nama'            => 'Bahan Habis Pakai dan Peralatan',
                'nama_form'       => 'bahan_habis_pakai_dan_peralatan',
                'id_sumberdana'   => 4,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 11,
                'nama'            => 'Biaya Transportasi dan Perjalanan',
                'nama_form'       => 'biaya_transportasi_dan_perjalanan',
                'id_sumberdana'   => 4,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 12,
                'nama'            => 'Biaya Lainnya',
                'nama_form'       => 'biaya_lainnya',
                'id_sumberdana'   => 4,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 13,
                'nama'            => 'Bahan',
                'nama_form'       => 'bahan',
                'id_sumberdana'   => 5,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 14,
                'nama'            => 'Pengumpulan Data',
                'nama_form'       => 'pengumpulan_data',
                'id_sumberdana'   => 5,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 15,
                'nama'            => 'Analisis Data (Termasuk Sewa Peralatan)',
                'nama_form'       => 'analisis_data',
                'id_sumberdana'   => 5,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 16,
                'nama'            => 'Pelaporan, Luaran Wajib dan Luaran Tambahan',
                'nama_form'       => 'pelaporan_luaran_wajib_dan_luaran_tambahan',
                'id_sumberdana'   => 5,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 17,
                'nama'            => 'Lain-Lain',
                'nama_form'       => 'lain_lain',
                'id_sumberdana'   => 5,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 18,
                'nama'            => 'Honorarium Tenaga Peneliti/Pakar',
                'nama_form'       => 'honorarium_tenaga_peneliti_pakar',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 19,
                'nama'            => 'Peralatan Pendukung Terkait Langsung dengan Kegiatan',
                'nama_form'       => 'peralatan_pendukung_terkait_langsung_dengan_kegiatan',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 20,
                'nama'            => 'Bahan Prototype/Produksi Skala Terbatas/Bahan Habis Penelitian',
                'nama_form'       => 'bahan_prototype_produksi_skala_terbatas_bahan_habis_penelitian',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 21,
                'nama'            => 'Pendampingan/Alih Teknologi',
                'nama_form'       => 'pendampingan_alih_teknologi',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 22,
                'nama'            => 'Diskusi Terpumpun/Focus Group Discussion (FGD)',
                'nama_form'       => 'diskusi_terpumpun_focus_group_discussion_fgd',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 23,
                'nama'            => 'Survei',
                'nama_form'       => 'survei',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 24,
                'nama'            => 'Biaya Pengujian Produk',
                'nama_form'       => 'biaya_pengujian_produk',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 25,
                'nama'            => 'Pendaftaran HKI',
                'nama_form'       => 'pendaftaran_hki',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 26,
                'nama'            => 'Biaya Perjalanan Dinas',
                'nama_form'       => 'biaya_perjalanan_dinas',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 27,
                'nama'            => 'Biaya Intensif Mahasiswa',
                'nama_form'       => 'biaya_intensif_mahasiswa',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 28,
                'nama'            => 'Biaya Produksi Skala Terbatas',
                'nama_form'       => 'biaya_produksi_skala_terbatas',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 29,
                'nama'            => 'Pengelolaan Program Dana Padanan',
                'nama_form'       => 'pengelolaan_program_dana_padanan',
                'id_sumberdana'   => 6,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 30,
                'nama'            => 'Biaya Langsung',
                'nama_form'       => 'biaya_langsung',
                'id_sumberdana'   => 7,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 31,
                'nama'            => 'Biaya Personil',
                'nama_form'       => 'biaya_personil',
                'id_sumberdana'   => 7,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 32,
                'nama'            => 'Biaya Non Personil',
                'nama_form'       => 'biaya_non_personil',
                'id_sumberdana'   => 7,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ], [
                'id'              => 33,
                'nama'            => 'Biaya Tak Langsung',
                'nama_form'       => 'biaya_tak_langsung',
                'id_sumberdana'   => 7,
                'user_id_created' => 1,
                'user_id_updated' => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ]);
    }
}
